### ISSUE TITLE
Cousera scraper 504

### ISSUE THREAD

**Issue by fbacall** [ElixirTeSS/TeSS_scrapers#54] opened 2018-02-16 09:12 UTC
A 504 error occurs when attempting to access:  https://api.coursera.org/api/courses.v1/?q=search&query=bioinformatics&limit=10

The main API endpoint seems to work though: https://api.coursera.org/api/courses.v1/

Did they change their API?

```
CourseraScraper: 504 Gateway Timeout
	/home/tess/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open-uri.rb:358:in `open_http'
	/home/tess/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
	/home/tess/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
	/home/tess/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
	/home/tess/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
	/home/tess/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
	/home/tess/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open-uri.rb:716:in `open'
	/home/tess/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open-uri.rb:34:in `open'
	/home/tess/TeSS_scrapers/lib/tess/scrapers/scraper.rb:87:in `open_url'
	/home/tess/TeSS_scrapers/app/scrapers/coursera_scraper.rb:44:in `parse_data'
	/home/tess/TeSS_scrapers/app/scrapers/coursera_scraper.rb:25:in `scrape'
	/home/tess/TeSS_scrapers/lib/tess/scrapers/scraper.rb:35:in `run'
	run_scrapers.rb:58:in `block in <main>'
	run_scrapers.rb:55:in `each'
	run_scrapers.rb:55:in `<main>'
```

**Comment by knirirr** [comment] 2018-03-02 14:54
I'm not able to reproduce this error whilst working from home, running the scraper on a BT Broadband connection and updating tess.oerc.

Though I wouldn't immediately have expected a 504 to mean this, I wonder if they're blocking us or there's some other network issue from the production server.

**Comment by knirirr** [comment] 2018-03-05 11:30
Closed as it appears to have resolved by itself.

**Closed by knirirr** 2018-03-05 11:30 UTC
